/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_plutinosoft_platinum_UPnP */

#ifndef _Included_com_plutinosoft_platinum_UPnP
#define _Included_com_plutinosoft_platinum_UPnP
#ifdef __cplusplus
extern "C" {
#endif

#define javaClassName "com/plutinosoft/platinum/UPnP"

static struct {
    jmethodID onDmsAdded;
    jmethodID onDmsRemoved;
    jmethodID onDmrAdded;
    jmethodID onDmrRemoved;
} gNativeUpnpClassInfo;

#define FIND_CLASS(var, className) \
        var = env->FindClass(className);

#define GET_METHOD_ID(var, clazz, methodName, fieldDescriptor) \
        var = env->GetMethodID(clazz, methodName, fieldDescriptor);


int register_NativeUpnp(JNIEnv *env);
int callBack_AddDms(const char* uuid, const char* friendName, const char* deviceType);
int callBack_AddDmr(const char* uuid, const char* friendName, const char* deviceType);




#ifdef __cplusplus
}
#endif
#endif
