/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_plutinosoft_platinum_UPnP */

#ifndef _Included_com_plutinosoft_platinum_UPnP
#define _Included_com_plutinosoft_platinum_UPnP
#ifdef __cplusplus
extern "C" {
#endif

#define javaClassName "com/plutinosoft/platinum/UPnP"


#ifdef __cplusplus
}
#endif
#endif
